/**
 * Coolify API Client
 *
 * Handles all interactions with the Coolify v4 API for deploying
 * static sites generated by the builder.
 *
 * Required env vars:
 *   COOLIFY_API_URL    — e.g. https://coolify.jlstudio.dev
 *   COOLIFY_API_TOKEN  — Bearer token from Coolify dashboard
 *   COOLIFY_SERVER_UUID — Target server UUID
 *   COOLIFY_PROJECT_UUID — Project UUID to group all client sites
 */

const COOLIFY_API_URL = process.env.COOLIFY_API_URL || ''
const COOLIFY_API_TOKEN = process.env.COOLIFY_API_TOKEN || ''
const COOLIFY_SERVER_UUID = process.env.COOLIFY_SERVER_UUID || ''
const COOLIFY_PROJECT_UUID = process.env.COOLIFY_PROJECT_UUID || ''
const GITHUB_TOKEN = process.env.GITHUB_DEPLOY_TOKEN || ''
const GITHUB_ORG = process.env.GITHUB_DEPLOY_ORG || 'jeason45'

// ─────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────

export interface CoolifyApp {
  uuid: string
  name: string
  fqdn: string
  status: string
  git_repository: string
  git_branch: string
}

export interface CoolifyDeployment {
  id: number
  deployment_uuid: string
  status: string
  created_at: string
  updated_at: string
}

export interface DeployResult {
  success: boolean
  appUuid?: string
  deploymentUuid?: string
  deployUrl?: string
  error?: string
}

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────

function isConfigured(): boolean {
  return !!(COOLIFY_API_URL && COOLIFY_API_TOKEN && COOLIFY_SERVER_UUID && COOLIFY_PROJECT_UUID)
}

async function coolifyFetch<T = unknown>(
  path: string,
  options: RequestInit = {},
): Promise<T> {
  const url = `${COOLIFY_API_URL}/api/v1${path}`
  const res = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${COOLIFY_API_TOKEN}`,
      ...options.headers,
    },
  })

  if (!res.ok) {
    const body = await res.text()
    throw new Error(`Coolify API ${res.status}: ${body}`)
  }

  const text = await res.text()
  return text ? JSON.parse(text) : ({} as T)
}

// ─────────────────────────────────────────────
// GITHUB — Push exported HTML to a deploy repo
// ─────────────────────────────────────────────

async function githubFetch<T = unknown>(
  path: string,
  options: RequestInit = {},
): Promise<T> {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      'X-GitHub-Api-Version': '2022-11-28',
      ...options.headers,
    },
  })

  if (!res.ok) {
    const body = await res.text()
    throw new Error(`GitHub API ${res.status}: ${body}`)
  }

  return res.json() as Promise<T>
}

/**
 * Ensure a GitHub repo exists for this site slug.
 * Creates it if it doesn't exist.
 */
async function ensureGitHubRepo(slug: string): Promise<string> {
  const repoName = `site-${slug}`
  const fullName = `${GITHUB_ORG}/${repoName}`

  try {
    await githubFetch(`/repos/${fullName}`)
    return fullName
  } catch {
    // Repo doesn't exist, create it
    await githubFetch('/user/repos', {
      method: 'POST',
      body: JSON.stringify({
        name: repoName,
        description: `Static site: ${slug} — deployed by JL Studio Builder`,
        private: true,
        auto_init: true,
      }),
    })
    return fullName
  }
}

/**
 * Push all exported files to the GitHub deploy repo.
 * Uses the GitHub Trees API for atomic commits.
 */
export async function pushToGitHub(
  slug: string,
  files: Array<{ path: string; content: string }>,
): Promise<{ repoFullName: string; commitSha: string }> {
  if (!GITHUB_TOKEN) {
    throw new Error('GITHUB_DEPLOY_TOKEN is not configured')
  }

  const repoFullName = await ensureGitHubRepo(slug)

  // Get the current HEAD SHA
  let headSha: string
  let treeSha: string
  try {
    const ref = await githubFetch<{ object: { sha: string } }>(
      `/repos/${repoFullName}/git/ref/heads/main`,
    )
    headSha = ref.object.sha
    const commit = await githubFetch<{ tree: { sha: string } }>(
      `/repos/${repoFullName}/git/commits/${headSha}`,
    )
    treeSha = commit.tree.sha
  } catch {
    // Empty repo — get default branch
    const repo = await githubFetch<{ default_branch: string }>(
      `/repos/${repoFullName}`,
    )
    const ref = await githubFetch<{ object: { sha: string } }>(
      `/repos/${repoFullName}/git/ref/heads/${repo.default_branch}`,
    )
    headSha = ref.object.sha
    const commit = await githubFetch<{ tree: { sha: string } }>(
      `/repos/${repoFullName}/git/commits/${headSha}`,
    )
    treeSha = commit.tree.sha
  }

  // Create blobs for each file
  const treeItems = await Promise.all(
    files.map(async (file) => {
      const blob = await githubFetch<{ sha: string }>(
        `/repos/${repoFullName}/git/blobs`,
        {
          method: 'POST',
          body: JSON.stringify({
            content: Buffer.from(file.content).toString('base64'),
            encoding: 'base64',
          }),
        },
      )
      return {
        path: file.path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blob.sha,
      }
    }),
  )

  // Create tree
  const tree = await githubFetch<{ sha: string }>(
    `/repos/${repoFullName}/git/trees`,
    {
      method: 'POST',
      body: JSON.stringify({
        base_tree: treeSha,
        tree: treeItems,
      }),
    },
  )

  // Create commit
  const commit = await githubFetch<{ sha: string }>(
    `/repos/${repoFullName}/git/commits`,
    {
      method: 'POST',
      body: JSON.stringify({
        message: `deploy: ${new Date().toISOString()}`,
        tree: tree.sha,
        parents: [headSha],
      }),
    },
  )

  // Update ref
  await githubFetch(`/repos/${repoFullName}/git/refs/heads/main`, {
    method: 'PATCH',
    body: JSON.stringify({ sha: commit.sha }),
  })

  return { repoFullName, commitSha: commit.sha }
}

// ─────────────────────────────────────────────
// COOLIFY — Application management
// ─────────────────────────────────────────────

/**
 * Create a new static site application in Coolify.
 */
export async function createCoolifyApp(
  slug: string,
  repoFullName: string,
  domain: string,
): Promise<{ uuid: string }> {
  if (!isConfigured()) throw new Error('Coolify not configured')

  const result = await coolifyFetch<{ uuid: string }>('/applications/public', {
    method: 'POST',
    body: JSON.stringify({
      project_uuid: COOLIFY_PROJECT_UUID,
      server_uuid: COOLIFY_SERVER_UUID,
      environment_name: 'production',
      git_repository: `https://github.com/${repoFullName}.git`,
      git_branch: 'main',
      build_pack: 'static',
      ports_exposes: '80',
      name: `site-${slug}`,
      domains: `https://${slug}.jlstudio.dev`,
      is_static: true,
      publish_directory: '/',
      static_image: 'nginx:alpine',
      is_force_https_enabled: true,
      is_auto_deploy_enabled: false,
      instant_deploy: false,
    }),
  })

  // If custom domain provided, set it
  if (domain && domain !== `${slug}.jlstudio.dev`) {
    await updateCoolifyAppDomain(result.uuid, domain)
  }

  return result
}

/**
 * Update the domain of a Coolify application.
 */
export async function updateCoolifyAppDomain(
  appUuid: string,
  domain: string,
): Promise<void> {
  if (!isConfigured()) throw new Error('Coolify not configured')

  await coolifyFetch(`/applications/${appUuid}`, {
    method: 'PATCH',
    body: JSON.stringify({
      domains: `https://${domain}`,
      is_force_https_enabled: true,
    }),
  })
}

/**
 * Trigger a deploy for an existing Coolify application.
 */
export async function triggerCoolifyDeploy(
  appUuid: string,
  force = false,
): Promise<{ deploymentUuid: string }> {
  if (!isConfigured()) throw new Error('Coolify not configured')

  const query = force ? `?uuid=${appUuid}&force=true` : `?uuid=${appUuid}`
  const result = await coolifyFetch<{
    deployments: Array<{ deployment_uuid: string }>
  }>(`/deploy${query}`)

  const deploymentUuid = result.deployments?.[0]?.deployment_uuid
  if (!deploymentUuid) {
    throw new Error('No deployment UUID returned from Coolify')
  }

  return { deploymentUuid }
}

/**
 * Get the status of a specific deployment.
 */
export async function getCoolifyDeploymentStatus(
  deploymentUuid: string,
): Promise<CoolifyDeployment> {
  if (!isConfigured()) throw new Error('Coolify not configured')

  return coolifyFetch<CoolifyDeployment>(`/deployments/${deploymentUuid}`)
}

/**
 * Get details of a Coolify application.
 */
export async function getCoolifyApp(
  appUuid: string,
): Promise<CoolifyApp> {
  if (!isConfigured()) throw new Error('Coolify not configured')

  return coolifyFetch<CoolifyApp>(`/applications/${appUuid}`)
}

/**
 * Delete a Coolify application.
 */
export async function deleteCoolifyApp(appUuid: string): Promise<void> {
  if (!isConfigured()) throw new Error('Coolify not configured')

  await coolifyFetch(`/applications/${appUuid}`, { method: 'DELETE' })
}

// ─────────────────────────────────────────────
// MAIN DEPLOY ORCHESTRATOR
// ─────────────────────────────────────────────

/**
 * Full deploy pipeline:
 * 1. Push exported files to GitHub
 * 2. Create or reuse Coolify app
 * 3. Trigger Coolify deployment
 *
 * Returns immediately after triggering — caller should poll status.
 */
export async function deploySiteToCoolify(
  slug: string,
  files: Array<{ path: string; content: string }>,
  existingAppUuid?: string | null,
  customDomain?: string,
): Promise<DeployResult> {
  try {
    // Step 1: Push to GitHub
    console.log(`[Deploy] Pushing ${files.length} files to GitHub for "${slug}"...`)
    const { repoFullName } = await pushToGitHub(slug, files)
    console.log(`[Deploy] Pushed to ${repoFullName}`)

    // Step 2: Create or reuse Coolify app
    let appUuid = existingAppUuid || ''
    const domain = customDomain || `${slug}.jlstudio.dev`

    if (!appUuid) {
      console.log(`[Deploy] Creating Coolify app for "${slug}"...`)
      const app = await createCoolifyApp(slug, repoFullName, domain)
      appUuid = app.uuid
      console.log(`[Deploy] Created Coolify app: ${appUuid}`)
    }

    // Step 3: Trigger deploy
    console.log(`[Deploy] Triggering Coolify deploy for "${slug}" (${appUuid})...`)
    const { deploymentUuid } = await triggerCoolifyDeploy(appUuid, true)
    console.log(`[Deploy] Deploy triggered: ${deploymentUuid}`)

    return {
      success: true,
      appUuid,
      deploymentUuid,
      deployUrl: `https://${domain}`,
    }
  } catch (error) {
    console.error(`[Deploy] Failed for "${slug}":`, error)
    return {
      success: false,
      error: String(error),
    }
  }
}

/**
 * Check if Coolify integration is configured.
 */
export function isCoolifyConfigured(): boolean {
  return isConfigured() && !!GITHUB_TOKEN
}
