import type { SectionStyle } from '@/types/site'

export interface VariantDef {
  id: string
  label: string
  description: string
  previewStyle: SectionStyle
}

export const SECTION_VARIANTS: Record<string, VariantDef[]> = {
  hero: [
    { id: 'startup', label: 'Startup / SaaS', description: 'Glow radial, CTA gradient, moderne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate', label: 'Corporate', description: 'Split navy, structuré, professionnel', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe', label: 'Luxe', description: 'Image plein écran, typo fine, overlay', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'creative', label: 'Créatif', description: 'Néobrutalist, bold, asymétrique', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce', label: 'E-commerce', description: 'Produit, prix, confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass', label: 'Glass / Tech', description: 'Glassmorphism, grid, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa', label: 'Brixsa — Immobilier', description: 'Slider plein écran, searchbox glassmorphism, crème', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'obscura', label: 'Obscura — Photographe', description: 'Slider plein écran, diagonal wipe, compteur doré, barre de progression', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'canopy', label: 'Canopy — Eco E-commerce', description: 'Split produit, coins carrés, vert forêt, éco-minimaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'braise', label: 'Braise — Restaurant', description: 'Slider plein \u00E9cran, noir profond, or chaud, gastronomique', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'forge', label: 'Forge — Coach Sportif', description: 'Slider plein \u00E9cran, noir profond, orange \u00E9lectrique, fitness', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'ciseaux', label: 'Ciseaux — Salon de Coiffure', description: 'Slider plein \u00E9cran, noir profond, cuivr\u00E9 rose gold, coiffure', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'atelier', label: 'Atelier — Architecte d\u2019int\u00E9rieur', description: 'Slider plein \u00E9cran, charcoal, sable/bronze, architecture int\u00E9rieure', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'encre', label: 'Encre (Tatoueur)', description: 'Slider plein \u00E9cran, noir profond, cramoisi, tatoueur', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'serenite', label: 'S\u00E9r\u00E9nit\u00E9 (Spa)', description: 'Slider plein \u00E9cran, navy profond, or chaud/lavande, institut & spa', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'pulse', label: 'Pulse (DJ)', description: 'Slider plein \u00E9cran, noir absolu, cyan n\u00E9on/magenta, DJ & musicien', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  features: [
    // Startup / SaaS
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Cards clean, ombres, glow accent', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-bento', label: 'Startup — Bento', description: 'Grille asymétrique, badges', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-list', label: 'Startup — Liste', description: 'Alternant icône/texte aéré', previewStyle: { background: 'white', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Cards structurées, navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-bento', label: 'Corporate — Bento', description: 'Asymétrique, bordure accent', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-list', label: 'Corporate — Liste', description: 'Liste sobre, séparateurs', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Espacement XXL, dividers dorés', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-bento', label: 'Luxe — Bento', description: 'Grandes cartes numérotées', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-list', label: 'Luxe — Liste', description: 'Liste numérotée élégante', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Bordures épaisses, offset shadow', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-bento', label: 'Créatif — Bento', description: 'Bento wild, stickers', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-list', label: 'Créatif — Liste', description: 'Gros numéros bold, uppercase', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Cards badges, étoiles', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-bento', label: 'E-commerce — Bento', description: 'Highlights produit', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-list', label: 'E-commerce — Liste', description: 'Checklist confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass / Tech
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Cards glassmorphism, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-bento', label: 'Glass — Bento', description: 'Glass bento, gradient borders', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-list', label: 'Glass — Liste', description: 'Liste dark, gradient text', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-accordion', label: 'Brixsa — Accordéon', description: 'Accordéon horizontal, 3 panneaux image, hover expand', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'brixsa-location', label: 'Brixsa — Location', description: 'Villes en gros H2, hover image portrait, dark atmosphérique', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'canopy-values', label: 'Canopy — Valeurs', description: 'Piliers éco-responsables, icônes rondes, coins carrés', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'braise-accordion', label: 'Braise — Accord\u00E9on Menu', description: 'Accord\u00E9on horizontal, 3 panneaux plats, restaurant gastronomique, noir/or', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'forge-accordion', label: 'Forge — Accord\u00E9on Coach', description: 'Accord\u00E9on horizontal, 3 panneaux, coach sportif, noir/orange', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'ciseaux-accordion', label: 'Ciseaux — Accord\u00E9on Coiffure', description: 'Accord\u00E9on horizontal, 3 panneaux, salon de coiffure, noir/cuivr\u00E9', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'atelier-accordion', label: 'Atelier — Accord\u00E9on Services', description: 'Accord\u00E9on horizontal, 3 panneaux, architecture int\u00E9rieure, charcoal/sable', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'encre-accordion', label: 'Encre Accordion', description: 'Accord\u00E9on horizontal, 3 panneaux, tatoueur, noir profond/cramoisi', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'serenite-accordion', label: 'S\u00E9r\u00E9nit\u00E9 Accordion', description: 'Accord\u00E9on horizontal, 3 panneaux, institut & spa, navy/or chaud', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'pulse-accordion', label: 'Pulse Accordion', description: 'Accord\u00E9on horizontal, 3 panneaux, DJ & musicien, noir absolu/cyan n\u00E9on', previewStyle: { background: 'dark', paddingY: 'lg' } },
  ],
  cta: [
    // Startup
    { id: 'startup-centered', label: 'Startup — Centré', description: 'CTA gradient, glow, moderne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-split', label: 'Startup — Split', description: 'Texte + boutons côte à côte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-card', label: 'Startup — Carte', description: 'Carte dégradée indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-centered', label: 'Corporate — Centré', description: 'Navy, structuré, pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-split', label: 'Corporate — Split', description: 'Texte + boutons, navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-card', label: 'Corporate — Carte', description: 'Carte navy accent bleu', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-centered', label: 'Luxe — Centré', description: 'Divider doré, élégant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-split', label: 'Luxe — Split', description: 'Texte + bouton doré', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-card', label: 'Luxe — Carte', description: 'Carte bordure dorée', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-centered', label: 'Créatif — Centré', description: 'Crème, bold, brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-split', label: 'Créatif — Split', description: 'Néobrutalist split', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-card', label: 'Créatif — Carte', description: 'Carte offset shadow', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-centered', label: 'E-commerce — Centré', description: 'Vert, urgence, confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-split', label: 'E-commerce — Split', description: 'Texte + CTA vert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-card', label: 'E-commerce — Carte', description: 'Carte promo verte', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-centered', label: 'Glass — Centré', description: 'Dark, glow, gradient text', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-split', label: 'Glass — Split', description: 'Glassmorphism split', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-card', label: 'Glass — Carte', description: 'Carte glassmorphism, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'obscura-centered', label: 'Obscura — Centré', description: 'CTA image fond, overlay noir, bouton or outline, photographe', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'nacre-centered', label: 'Nacre — Centr\u00E9', description: 'CTA image fond, overlay bordeaux, dor\u00E9/rose poudr\u00E9', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-centered', label: 'Brixsa — Centré', description: 'CTA image fond, overlay noir, crème/brun', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'canopy-banner', label: 'Canopy — Bannière', description: 'Bannière éco pleine largeur, vert forêt, coins carrés', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  stats: [
    { id: 'startup-simple', label: 'Startup — Simple', description: 'Chiffres en ligne, moderne', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'startup-cards', label: 'Startup — Cards', description: 'Cartes individuelles', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'startup-highlight', label: 'Startup — Highlight', description: 'Stat principale + secondaires', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-simple', label: 'Corporate — Simple', description: 'Navy, professionnel', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-cards', label: 'Corporate — Cards', description: 'Cartes pro, accent bleu', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-highlight', label: 'Corporate — Highlight', description: 'Stat mise en avant, navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-simple', label: 'Luxe — Simple', description: 'Doré, élégant, minimaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-cards', label: 'Luxe — Cards', description: 'Cartes dorées raffinées', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-highlight', label: 'Luxe — Highlight', description: 'Grand chiffre doré central', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-simple', label: 'Créatif — Simple', description: 'Bold, crème, énorme typo', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'creative-cards', label: 'Créatif — Cards', description: 'Cartes offset shadow', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'creative-highlight', label: 'Créatif — Highlight', description: 'Stat géante + petites cartes', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'ecommerce-simple', label: 'E-commerce — Simple', description: 'Vert confiance, en ligne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-cards', label: 'E-commerce — Cards', description: 'Cartes trust + check', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-highlight', label: 'E-commerce — Highlight', description: 'KPI principal + secondaires', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-simple', label: 'Glass — Simple', description: 'Glassmorphism, gradient text', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-cards', label: 'Glass — Cards', description: 'Cartes verre, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-highlight', label: 'Glass — Highlight', description: 'Stat glow centrale', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'review-stars', label: 'Avis / Stars', description: 'Note moyenne + sources', previewStyle: { background: 'white', paddingY: 'md' } },
  ],
  testimonials: [
    // Startup
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Cards clean, étoiles amber', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'startup-featured', label: 'Startup — Featured', description: 'Un grand + petits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-marquee', label: 'Startup — Marquee', description: 'Défilement infini', previewStyle: { background: 'light', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Cards navy, bordure bleue', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-featured', label: 'Corporate — Featured', description: 'Témoignage principal, navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-marquee', label: 'Corporate — Marquee', description: 'Défilement navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Italique, doré, élégant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-featured', label: 'Luxe — Featured', description: 'Citation principale dorée', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-marquee', label: 'Luxe — Marquee', description: 'Défilement élégant', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Bordures épaisses, crème', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-featured', label: 'Créatif — Featured', description: 'Citation bold, offset', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-marquee', label: 'Créatif — Marquee', description: 'Défilement brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Achat vérifié, étoiles', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-featured', label: 'E-commerce — Featured', description: 'Avis principal, confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-marquee', label: 'E-commerce — Marquee', description: 'Défilement avis clients', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Glassmorphism, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-featured', label: 'Glass — Featured', description: 'Citation glass, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-marquee', label: 'Glass — Marquee', description: 'Défilement dark glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Slider
    { id: 'startup-slider', label: 'Startup — Slider', description: 'Carousel temoignages indigo', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'corporate-slider', label: 'Corporate — Slider', description: 'Carousel temoignages navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-slider', label: 'Luxe — Slider', description: 'Carousel temoignages dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-slider', label: 'Creatif — Slider', description: 'Carousel temoignages brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-slider', label: 'E-commerce — Slider', description: 'Carousel avis clients', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-slider', label: 'Glass — Slider', description: 'Carousel temoignages glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'obscura-featured', label: 'Obscura — Featured', description: '50/50 initiales or + citation, noir profond/or chaud', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'nacre-featured', label: 'Nacre — Featured', description: '50/50 initiales dor\u00E9es + citation, rose poudr\u00E9/bordeaux', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-featured', label: 'Brixsa — Featured', description: '50/50 image + citation, fond noir, crème', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'canopy-cards', label: 'Canopy — Cards', description: 'Avis clients, cards blanches, coins carr\u00E9s, \u00E9toiles', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'braise-featured', label: 'Braise — T\u00E9moignages', description: '50/50 initiales or + citation, noir profond/or chaud, restaurant', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'forge-featured', label: 'Forge — T\u00E9moignages', description: '50/50 initiales orange + citation, noir profond/orange, coach sportif', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'ciseaux-featured', label: 'Ciseaux — T\u00E9moignages', description: '50/50 initiales cuivr\u00E9es + citation, noir profond/cuivr\u00E9, salon coiffure', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'atelier-featured', label: 'Atelier — T\u00E9moignages', description: '50/50 initiales sable + citation, charcoal/sable, architecte int\u00E9rieur', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'encre-featured', label: 'Encre Featured', description: '50/50 initiales cramoisi + citation, noir profond/cramoisi, tatoueur', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'serenite-featured', label: 'S\u00E9r\u00E9nit\u00E9 Featured', description: '50/50 initiales dor\u00E9es + citation, navy profond/or chaud, institut & spa', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'pulse-featured', label: 'Pulse Featured', description: '50/50 initiales cyan + citation, noir absolu/cyan n\u00E9on, DJ & musicien', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  pricing: [
    // Startup
    { id: 'startup-columns', label: 'Startup — Colonnes', description: 'Cards modernes, pill badge', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-comparison', label: 'Startup — Comparaison', description: 'Tableau comparatif', previewStyle: { background: 'white', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-columns', label: 'Corporate — Colonnes', description: 'Cards navy pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-comparison', label: 'Corporate — Comparaison', description: 'Tableau navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-columns', label: 'Luxe — Colonnes', description: 'Cards dorées élégantes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-comparison', label: 'Luxe — Comparaison', description: 'Tableau doré', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-columns', label: 'Créatif — Colonnes', description: 'Cards brutalistes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-comparison', label: 'Créatif — Comparaison', description: 'Tableau néobrutalist', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-columns', label: 'E-commerce — Colonnes', description: 'Meilleure offre, savings', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-comparison', label: 'E-commerce — Comparaison', description: 'Tableau trust badges', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-columns', label: 'Glass — Colonnes', description: 'Cards glassmorphism', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-comparison', label: 'Glass — Comparaison', description: 'Tableau glassmorphism', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  faq: [
    // Startup
    { id: 'startup-accordion', label: 'Startup — Accordéon', description: 'Clean, indigo, accordéon moderne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Cards Q/A en grille', previewStyle: { background: 'light', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-accordion', label: 'Corporate — Accordéon', description: 'Navy, structuré, professionnel', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Cards navy, grille pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-accordion', label: 'Luxe — Accordéon', description: 'Doré, élégant, dividers', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Cards dorées raffinées', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-accordion', label: 'Créatif — Accordéon', description: 'Bordures épaisses, crème', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Cards offset, brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-accordion', label: 'E-commerce — Accordéon', description: 'Vert confiance, FAQ achat', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Cards FAQ produit', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-accordion', label: 'Glass — Accordéon', description: 'Glassmorphism, dark, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Cards glassmorphism', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  contact: [
    // Startup
    { id: 'startup-simple', label: 'Startup — Simple', description: 'Formulaire clean, indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-with-info', label: 'Startup — Avec infos', description: 'Formulaire + coordonnées', previewStyle: { background: 'white', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-simple', label: 'Corporate — Simple', description: 'Navy, structuré', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-with-info', label: 'Corporate — Avec infos', description: 'Navy, formulaire + infos', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-simple', label: 'Luxe — Simple', description: 'Doré, élégant, minimaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-with-info', label: 'Luxe — Avec infos', description: 'Doré, formulaire + coordonnées', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-simple', label: 'Créatif — Simple', description: 'Crème, bordures épaisses', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-with-info', label: 'Créatif — Avec infos', description: 'Brutaliste, formulaire + infos', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-simple', label: 'E-commerce — Simple', description: 'Vert, confiance, badge', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-with-info', label: 'E-commerce — Avec infos', description: 'Vert, formulaire + support', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-simple', label: 'Glass — Simple', description: 'Glassmorphism, dark', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-with-info', label: 'Glass — Avec infos', description: 'Glass, formulaire + infos glow', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  logos: [
    // Startup
    { id: 'startup-strip', label: 'Startup — Rangée', description: 'Logos en ligne, moderne', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Grille cards logo', previewStyle: { background: 'light', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-strip', label: 'Corporate — Rangée', description: 'Navy, logos sobres', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Grille navy structurée', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-strip', label: 'Luxe — Rangée', description: 'Dividers dorés, élégant', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Grille dorée raffinée', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-strip', label: 'Créatif — Rangée', description: 'Bordures épaisses, crème', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Cards offset, brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-strip', label: 'E-commerce — Rangée', description: 'Vert, partenaires confiance', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Grille marques vérifiées', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-strip', label: 'Glass — Rangée', description: 'Dark, glow logos', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Cards glassmorphism', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  team: [
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Cards modernes, indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-list', label: 'Startup — Liste', description: 'Lignes horizontales', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Navy, cards pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-list', label: 'Corporate — Liste', description: 'Navy, lignes structurées', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Doré, élégant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-list', label: 'Luxe — Liste', description: 'Doré, dividers', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Brutaliste, offset', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-list', label: 'Créatif — Liste', description: 'Néobrutalist, bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Vert, badges vérifiés', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-list', label: 'E-commerce — Liste', description: 'Vert, lignes confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Glassmorphism, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-list', label: 'Glass — Liste', description: 'Glass, dark lignes', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-marquee', label: 'Brixsa — Marquee', description: 'Marquee infini agents, portraits, crème', previewStyle: { background: 'white', paddingY: 'md' } },
  ],
  'blog-grid': [
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Cards articles, indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-featured', label: 'Startup — Featured', description: '1 grand + petits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Navy, articles pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-featured', label: 'Corporate — Featured', description: 'Navy, article principal', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Doré, articles élégants', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-featured', label: 'Luxe — Featured', description: 'Doré, article en vedette', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Brutaliste, articles bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-featured', label: 'Créatif — Featured', description: 'Néobrutalist, hero post', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Vert, articles vérifiés', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-featured', label: 'E-commerce — Featured', description: 'Vert, article principal', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Glass, articles dark', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-featured', label: 'Glass — Featured', description: 'Glass, hero article glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-grid', label: 'Brixsa — Journal', description: 'Grid 2 colonnes, crème, tags immobilier', previewStyle: { background: 'white', paddingY: 'md' } },
  ],
  timeline: [
    { id: 'startup-vertical', label: 'Startup — Vertical', description: 'Timeline indigo moderne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-alternating', label: 'Startup — Alternant', description: 'Gauche/droite indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-vertical', label: 'Corporate — Vertical', description: 'Navy, structuré', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-alternating', label: 'Corporate — Alternant', description: 'Navy, cards alternées', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-vertical', label: 'Luxe — Vertical', description: 'Doré, ligne élégante', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-alternating', label: 'Luxe — Alternant', description: 'Doré, alternant raffiné', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-vertical', label: 'Créatif — Vertical', description: 'Brutaliste, ligne épaisse', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-alternating', label: 'Créatif — Alternant', description: 'Offset shadow, alternant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-vertical', label: 'E-commerce — Vertical', description: 'Vert, milestones', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-alternating', label: 'E-commerce — Alternant', description: 'Vert, alternant confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-vertical', label: 'Glass — Vertical', description: 'Dark, glow timeline', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-alternating', label: 'Glass — Alternant', description: 'Glass, alternant glow', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  steps: [
    { id: 'startup-horizontal', label: 'Startup — Horizontal', description: 'Étapes indigo modernes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-vertical', label: 'Startup — Vertical', description: 'Étapes empilées indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-horizontal', label: 'Corporate — Horizontal', description: 'Navy, étapes pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-vertical', label: 'Corporate — Vertical', description: 'Navy, empilé structuré', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-horizontal', label: 'Luxe — Horizontal', description: 'Doré, élégant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-vertical', label: 'Luxe — Vertical', description: 'Doré, empilé raffiné', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-horizontal', label: 'Créatif — Horizontal', description: 'Brutaliste, bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-vertical', label: 'Créatif — Vertical', description: 'Néobrutalist empilé', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-horizontal', label: 'E-commerce — Horizontal', description: 'Vert, étapes confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-vertical', label: 'E-commerce — Vertical', description: 'Vert, empilé vérifié', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-horizontal', label: 'Glass — Horizontal', description: 'Dark, glass étapes', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-vertical', label: 'Glass — Vertical', description: 'Glass, empilé glow', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  'gallery-grid': [
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Grille moderne, indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-masonry', label: 'Startup — Masonry', description: 'Masonry clean', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Navy, grille pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-masonry', label: 'Corporate — Masonry', description: 'Navy, masonry', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Doré, grille élégante', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-masonry', label: 'Luxe — Masonry', description: 'Doré, masonry raffiné', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Brutaliste, offset', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-masonry', label: 'Créatif — Masonry', description: 'Néobrutalist masonry', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Vert, images vérifiées', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-masonry', label: 'E-commerce — Masonry', description: 'Vert, masonry produits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Dark, glass grille', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-masonry', label: 'Glass — Masonry', description: 'Glass, masonry glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'nacre-services', label: 'Nacre — Services', description: 'Grid 3 colonnes, cards services salon ongles, rose poudr\u00E9', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'brixsa-listing', label: 'Brixsa — Property Listing', description: 'Grid 3 colonnes, cards portrait, badges, cr\u00E8me', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'braise-menu', label: 'Braise — Carte du Restaurant', description: 'Grid 3 colonnes, cards plats, noir profond/or, glassmorphism', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'forge-programs', label: 'Forge — Programmes', description: 'Grid 3 colonnes, cards programmes fitness, noir/orange', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'ciseaux-realisations', label: 'Ciseaux — R\u00E9alisations', description: 'Grid 3 colonnes, galerie coiffures, noir profond/cuivr\u00E9', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'atelier-projets', label: 'Atelier — Projets', description: 'Grid 3 colonnes, galerie projets architecture int\u00E9rieure, charcoal/sable', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'encre-portfolio', label: 'Encre Portfolio', description: 'Grid 3 colonnes, galerie tatouages, noir profond/cramoisi', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'serenite-soins', label: 'S\u00E9r\u00E9nit\u00E9 Soins', description: 'Grid 3 colonnes, galerie soins & rituels spa, navy profond/or chaud', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'pulse-events', label: 'Pulse Events', description: 'Grid 3 colonnes, galerie \u00E9v\u00E9nements DJ, noir absolu/cyan n\u00E9on, DJ & musicien', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  'image-text': [
    { id: 'startup-image-right', label: 'Startup — Image droite', description: 'Indigo, texte + image', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-image-left', label: 'Startup — Image gauche', description: 'Indigo, image + texte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-image-right', label: 'Corporate — Image droite', description: 'Navy, texte + image', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-image-left', label: 'Corporate — Image gauche', description: 'Navy, image + texte', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-image-right', label: 'Luxe — Image droite', description: 'Doré, texte + image', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-image-left', label: 'Luxe — Image gauche', description: 'Doré, image + texte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-image-right', label: 'Créatif — Image droite', description: 'Brutaliste, texte + image', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-image-left', label: 'Créatif — Image gauche', description: 'Brutaliste, image + texte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-image-right', label: 'E-commerce — Image droite', description: 'Vert, texte + image', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-image-left', label: 'E-commerce — Image gauche', description: 'Vert, image + texte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-image-right', label: 'Glass — Image droite', description: 'Dark, texte + image', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-image-left', label: 'Glass — Image gauche', description: 'Dark, image + texte', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-about', label: 'Brixsa — About', description: 'Layout asymétrique, counters animés, crème', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'brixsa-privacy', label: 'Brixsa — Privacy / Legal', description: 'Rich text, fond cr\u00E8me, sections num\u00E9rot\u00E9es, listes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'braise-story', label: 'Braise — Histoire du Chef', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, noir profond/or', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'forge-story', label: 'Forge — Bio du Coach', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, noir profond/orange', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'ciseaux-story', label: 'Ciseaux — Histoire du Salon', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, noir profond/cuivr\u00E9', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'atelier-story', label: 'Atelier — Histoire du Studio', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, charcoal/sable, architecte', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'encre-story', label: 'Encre Story', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, noir profond/cramoisi, tatoueur', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'serenite-story', label: 'S\u00E9r\u00E9nit\u00E9 Story', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, navy profond/or chaud, institut & spa', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'pulse-story', label: 'Pulse Story', description: 'Layout asym\u00E9trique, compteurs anim\u00E9s, noir absolu/cyan n\u00E9on, DJ & musicien', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  'product-grid': [
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Cards produits indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-list', label: 'Startup — Liste', description: 'Lignes produits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Navy, produits pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-list', label: 'Corporate — Liste', description: 'Navy, lignes produits', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Doré, produits élégants', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-list', label: 'Luxe — Liste', description: 'Doré, lignes raffinées', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-grid', label: 'Créatif — Grille', description: 'Brutaliste, produits bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-list', label: 'Créatif — Liste', description: 'Néobrutalist, lignes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Vert, produits confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-list', label: 'E-commerce — Liste', description: 'Vert, lignes produits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Dark, produits glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-list', label: 'Glass — Liste', description: 'Glass, lignes produits', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  newsletter: [
    // Startup
    { id: 'startup-centered', label: 'Startup — Centré', description: 'Clean, indigo, centré', previewStyle: { background: 'light', paddingY: 'md' } },
    { id: 'startup-split', label: 'Startup — Split', description: 'Texte + champ côte à côte', previewStyle: { background: 'white', paddingY: 'md' } },
    // Corporate
    { id: 'corporate-centered', label: 'Corporate — Centré', description: 'Navy, centré, pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-split', label: 'Corporate — Split', description: 'Navy, texte + champ', previewStyle: { background: 'dark', paddingY: 'md' } },
    // Luxe
    { id: 'luxe-centered', label: 'Luxe — Centré', description: 'Doré, élégant, centré', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-split', label: 'Luxe — Split', description: 'Doré, texte + champ', previewStyle: { background: 'white', paddingY: 'md' } },
    // Créatif
    { id: 'creative-centered', label: 'Créatif — Centré', description: 'Crème, bold, centré', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-split', label: 'Créatif — Split', description: 'Brutaliste, texte + champ', previewStyle: { background: 'white', paddingY: 'md' } },
    // E-commerce
    { id: 'ecommerce-centered', label: 'E-commerce — Centré', description: 'Vert, centré, confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-split', label: 'E-commerce — Split', description: 'Vert, texte + champ', previewStyle: { background: 'white', paddingY: 'md' } },
    // Glass
    { id: 'glass-centered', label: 'Glass — Centré', description: 'Dark, glassmorphism, centré', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-split', label: 'Glass — Split', description: 'Dark, glass, texte + champ', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'canopy-minimal', label: 'Canopy — Minimal', description: 'Inscription éco, coins carrés, vert forêt', previewStyle: { background: 'white', paddingY: 'md' } },
  ],
  'site-header': [
    { id: 'startup', label: 'Startup / SaaS', description: 'Nav pilules, CTA gradient, moderne', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'corporate', label: 'Corporate', description: 'Navy, structuré, professionnel', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'luxe', label: 'Luxe', description: 'Élégant, espacé, accents dorés', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'creative', label: 'Créatif', description: 'Néobrutalist, bold, audacieux', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'ecommerce', label: 'E-commerce', description: 'Recherche, panier, catégories', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'glass', label: 'Glass / Tech', description: 'Glassmorphism, dark, futuriste', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'brixsa', label: 'Brixsa — Immobilier', description: 'Transparent, glassmorphism menu, cr\u00E8me', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'braise', label: 'Braise — Restaurant', description: 'Transparent, noir profond, or chaud, gastronomique', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'forge', label: 'Forge — Coach Sportif', description: 'Transparent, noir profond, orange \u00E9lectrique, fitness', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'ciseaux', label: 'Ciseaux — Salon de Coiffure', description: 'Transparent, noir profond, cuivr\u00E9 rose gold, coiffure', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'atelier', label: 'Atelier — Architecte d\u2019int\u00E9rieur', description: 'Transparent, charcoal, sable/bronze, architecture int\u00E9rieure', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'encre', label: 'Encre (Tatoueur)', description: 'Transparent, noir profond, cramoisi, tatoueur', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'serenite', label: 'S\u00E9r\u00E9nit\u00E9 (Spa)', description: 'Transparent, navy profond, or chaud/lavande, institut & spa', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'pulse', label: 'Pulse (DJ)', description: 'Transparent, noir absolu, cyan n\u00E9on/magenta, DJ & musicien', previewStyle: { background: 'dark', paddingY: 'sm' } },
  ],
  'site-footer': [
    { id: 'startup', label: 'Startup / SaaS', description: 'Moderne, colonnes, status', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate', label: 'Corporate', description: 'Navy, structuré, liens légaux', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe', label: 'Luxe', description: 'Centré, espacé, divider doré', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'creative', label: 'Créatif', description: 'Néobrutalist, typo XXL, crème', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce', label: 'E-commerce', description: 'Newsletter + moyens de paiement', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass', label: 'Glass / Tech', description: 'Card glassmorphism, glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'obscura', label: 'Obscura — Photographe', description: 'Multi-colonne, noir profond, or chaud, text-mask hover', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa', label: 'Brixsa — Immobilier', description: 'Multi-colonne, liens H2, cr\u00E8me/brun', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'braise', label: 'Braise — Restaurant', description: 'Logo centr\u00E9, 3 colonnes, noir profond/or, TripAdvisor', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'forge', label: 'Forge — Coach Sportif', description: 'Logo centr\u00E9, 3 colonnes, noir profond/orange, YouTube/TikTok', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'ciseaux', label: 'Ciseaux — Salon de Coiffure', description: 'Logo centr\u00E9, 3 colonnes, noir profond/cuivr\u00E9, Pinterest', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'atelier', label: 'Atelier — Architecte d\u2019int\u00E9rieur', description: 'Logo centr\u00E9, 3 colonnes, charcoal/sable, Instagram/Pinterest/Houzz', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'encre', label: 'Encre (Tatoueur)', description: 'Logo centr\u00E9, 3 colonnes, noir profond/cramoisi, Instagram/TikTok/Facebook', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'serenite', label: 'S\u00E9r\u00E9nit\u00E9 (Spa)', description: 'Logo centr\u00E9, 3 colonnes, navy profond/or chaud, Instagram/Facebook/Pinterest', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'pulse', label: 'Pulse (DJ)', description: 'Logo centr\u00E9, 3 colonnes, noir absolu/cyan n\u00E9on, Instagram/SoundCloud/Spotify', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  tabs: [
    { id: 'startup-horizontal', label: 'Startup — Horizontal', description: 'Tabs pill indigo, horizontal', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-vertical', label: 'Startup — Vertical', description: 'Tabs pill indigo, vertical', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-horizontal', label: 'Corporate — Horizontal', description: 'Tabs navy, horizontal', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-vertical', label: 'Corporate — Vertical', description: 'Tabs navy, vertical', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-horizontal', label: 'Luxe — Horizontal', description: 'Line doree, horizontal', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-vertical', label: 'Luxe — Vertical', description: 'Line doree, vertical', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-horizontal', label: 'Creatif — Horizontal', description: 'Neobrutalist, jaune actif, horizontal', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-vertical', label: 'Creatif — Vertical', description: 'Neobrutalist, jaune actif, vertical', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-horizontal', label: 'E-commerce — Horizontal', description: 'Tabs rounded vert, horizontal', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-vertical', label: 'E-commerce — Vertical', description: 'Tabs rounded vert, vertical', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-horizontal', label: 'Glass — Horizontal', description: 'Glassmorphism glow, horizontal', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-vertical', label: 'Glass — Vertical', description: 'Glassmorphism glow, vertical', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'brixsa-horizontal', label: 'Brixsa — Expertise', description: '50/50 image + tabs, fond noir, crème', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  accordion: [
    { id: 'startup-single', label: 'Startup — Simple', description: 'Accordion indigo, un seul ouvert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-multi', label: 'Startup — Multiple', description: 'Accordion indigo, plusieurs ouverts', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-single', label: 'Corporate — Simple', description: 'Navy, un seul ouvert', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-multi', label: 'Corporate — Multiple', description: 'Navy, plusieurs ouverts', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-single', label: 'Luxe — Simple', description: 'Dore, un seul ouvert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-multi', label: 'Luxe — Multiple', description: 'Dore, plusieurs ouverts', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-single', label: 'Creatif — Simple', description: 'Neobrutalist, un seul ouvert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-multi', label: 'Creatif — Multiple', description: 'Neobrutalist, plusieurs ouverts', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-single', label: 'E-commerce — Simple', description: 'Vert, un seul ouvert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-multi', label: 'E-commerce — Multiple', description: 'Vert, plusieurs ouverts', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-single', label: 'Glass — Simple', description: 'Glassmorphism, un seul ouvert', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-multi', label: 'Glass — Multiple', description: 'Glassmorphism, plusieurs ouverts', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  lightbox: [
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Lightbox grille indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-masonry', label: 'Startup — Masonry', description: 'Lightbox masonry indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Lightbox grille navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-masonry', label: 'Corporate — Masonry', description: 'Lightbox masonry navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Lightbox grille dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-masonry', label: 'Luxe — Masonry', description: 'Lightbox masonry dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-grid', label: 'Creatif — Grille', description: 'Lightbox brutaliste grille', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-masonry', label: 'Creatif — Masonry', description: 'Lightbox brutaliste masonry', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-grid', label: 'E-commerce — Grille', description: 'Lightbox grille verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-masonry', label: 'E-commerce — Masonry', description: 'Lightbox masonry verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-grid', label: 'Glass — Grille', description: 'Lightbox grille glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-masonry', label: 'Glass — Masonry', description: 'Lightbox masonry glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  video: [
    { id: 'startup-full', label: 'Startup — Pleine largeur', description: 'Video pleine largeur indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-feature', label: 'Startup — Feature', description: 'Video + texte indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-full', label: 'Corporate — Pleine largeur', description: 'Video pleine largeur navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-feature', label: 'Corporate — Feature', description: 'Video + texte navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-full', label: 'Luxe — Pleine largeur', description: 'Video pleine largeur dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-feature', label: 'Luxe — Feature', description: 'Video + texte dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-full', label: 'Creatif — Pleine largeur', description: 'Video brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-feature', label: 'Creatif — Feature', description: 'Video + texte brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-full', label: 'E-commerce — Pleine largeur', description: 'Video pleine largeur verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-feature', label: 'E-commerce — Feature', description: 'Video + texte verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-full', label: 'Glass — Pleine largeur', description: 'Video glass dark', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-feature', label: 'Glass — Feature', description: 'Video + texte glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  slider: [
    { id: 'startup-hero', label: 'Startup — Hero', description: 'Slider plein ecran, overlay indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-cards', label: 'Startup — Cards', description: 'Slider cards, 3 visibles', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-thumbnails', label: 'Startup — Thumbnails', description: 'Slider + thumbnails', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-hero', label: 'Corporate — Hero', description: 'Slider hero navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-cards', label: 'Corporate — Cards', description: 'Cards navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-thumbnails', label: 'Corporate — Thumbnails', description: 'Thumbnails navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-hero', label: 'Luxe — Hero', description: 'Slider hero dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-cards', label: 'Luxe — Cards', description: 'Cards dorees', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-thumbnails', label: 'Luxe — Thumbnails', description: 'Thumbnails dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-hero', label: 'Creatif — Hero', description: 'Slider hero brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-cards', label: 'Creatif — Cards', description: 'Cards neobrutalist', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-thumbnails', label: 'Creatif — Thumbnails', description: 'Thumbnails bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-hero', label: 'E-commerce — Hero', description: 'Slider hero vert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-cards', label: 'E-commerce — Cards', description: 'Cards produits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-thumbnails', label: 'E-commerce — Thumbnails', description: 'Thumbnails produits', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-hero', label: 'Glass — Hero', description: 'Slider hero glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-cards', label: 'Glass — Cards', description: 'Cards glassmorphism', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-thumbnails', label: 'Glass — Thumbnails', description: 'Thumbnails glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'obscura-parallax', label: 'Obscura — Parallax Portfolio', description: 'Portfolio photo plein écran avec parallax, badges or glassmorphism, noir profond', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'nacre-parallax', label: 'Nacre — Parallax Gallery', description: 'Galerie nail art plein \u00E9cran avec parallax, badges glassmorphism, rose/dor\u00E9', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'canopy-parallax', label: 'Canopy — Parallax Products', description: 'Produits éco plein écran avec parallax, badges glassmorphism vert forêt', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'brixsa-parallax', label: 'Brixsa — Parallax Featured', description: 'Propri\u00E9t\u00E9s plein \u00E9cran avec parallax, badge Featured, prix', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'braise-parallax', label: 'Braise — Parallax Ambiance', description: 'Ambiance restaurant plein \u00E9cran avec parallax, noir profond/or', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'forge-parallax', label: 'Forge — Parallax Training', description: 'Ambiance fitness plein \u00E9cran avec parallax, noir profond/orange', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'ciseaux-parallax', label: 'Ciseaux — Parallax Salon', description: 'Ambiance salon coiffure plein \u00E9cran avec parallax, noir profond/cuivr\u00E9', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'atelier-parallax', label: 'Atelier — Parallax Int\u00E9rieur', description: 'Ambiance architecture int\u00E9rieure plein \u00E9cran avec parallax, charcoal/sable', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'encre-parallax', label: 'Encre Parallax', description: 'Ambiance tatoueur plein \u00E9cran avec parallax, noir profond/cramoisi', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'serenite-parallax', label: 'S\u00E9r\u00E9nit\u00E9 Parallax', description: 'Espaces spa plein \u00E9cran avec parallax, navy profond/or chaud, institut & spa', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'pulse-parallax', label: 'Pulse Parallax', description: 'Ambiance DJ plein \u00E9cran avec parallax, noir absolu/cyan n\u00E9on, DJ & musicien', previewStyle: { background: 'dark', paddingY: 'lg' } },
  ],
  dropdown: [
    { id: 'startup-simple', label: 'Startup — Simple', description: 'Dropdown simple indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-mega', label: 'Startup — Mega', description: 'Mega menu indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-simple', label: 'Corporate — Simple', description: 'Dropdown simple navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-mega', label: 'Corporate — Mega', description: 'Mega menu navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-simple', label: 'Luxe — Simple', description: 'Dropdown simple dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-mega', label: 'Luxe — Mega', description: 'Mega menu dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-simple', label: 'Creatif — Simple', description: 'Dropdown brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-mega', label: 'Creatif — Mega', description: 'Mega menu brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-simple', label: 'E-commerce — Simple', description: 'Dropdown simple vert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-mega', label: 'E-commerce — Mega', description: 'Mega menu vert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-simple', label: 'Glass — Simple', description: 'Dropdown glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-mega', label: 'Glass — Mega', description: 'Mega menu glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  'navbar-advanced': [
    { id: 'startup-standard', label: 'Startup — Standard', description: 'Navbar standard indigo', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'startup-mega', label: 'Startup — Mega', description: 'Navbar mega menu indigo', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'corporate-standard', label: 'Corporate — Standard', description: 'Navbar standard navy', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'corporate-mega', label: 'Corporate — Mega', description: 'Navbar mega navy', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'luxe-standard', label: 'Luxe — Standard', description: 'Navbar standard dore', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'luxe-mega', label: 'Luxe — Mega', description: 'Navbar mega dore', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'creative-standard', label: 'Creatif — Standard', description: 'Navbar brutaliste', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'creative-mega', label: 'Creatif — Mega', description: 'Navbar mega brutaliste', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'ecommerce-standard', label: 'E-commerce — Standard', description: 'Navbar standard vert', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'ecommerce-mega', label: 'E-commerce — Mega', description: 'Navbar mega vert', previewStyle: { background: 'white', paddingY: 'sm' } },
    { id: 'glass-standard', label: 'Glass — Standard', description: 'Navbar glass', previewStyle: { background: 'dark', paddingY: 'sm' } },
    { id: 'glass-mega', label: 'Glass — Mega', description: 'Navbar mega glass', previewStyle: { background: 'dark', paddingY: 'sm' } },
  ],
  'quick-stack': [
    { id: 'startup-1', label: 'Startup', description: 'Stack cards indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-2', label: 'Startup — Alt', description: 'Stack cards indigo variante', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-1', label: 'Corporate', description: 'Stack cards navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-2', label: 'Corporate — Alt', description: 'Stack cards navy variante', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-1', label: 'Luxe', description: 'Stack cards dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-2', label: 'Luxe — Alt', description: 'Stack cards dore variante', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-1', label: 'Creatif', description: 'Stack brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-2', label: 'Creatif — Alt', description: 'Stack brutaliste variante', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-1', label: 'E-commerce', description: 'Stack cards vert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-2', label: 'E-commerce — Alt', description: 'Stack cards vert variante', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-1', label: 'Glass', description: 'Stack glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-2', label: 'Glass — Alt', description: 'Stack glass variante', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  map: [
    { id: 'startup-full', label: 'Startup — Pleine', description: 'Carte pleine largeur indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-info', label: 'Startup — Info', description: 'Carte + infos indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-full', label: 'Corporate — Pleine', description: 'Carte pleine largeur navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-info', label: 'Corporate — Info', description: 'Carte + infos navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-full', label: 'Luxe — Pleine', description: 'Carte pleine largeur dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-info', label: 'Luxe — Info', description: 'Carte + infos dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-full', label: 'Creatif — Pleine', description: 'Carte brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-info', label: 'Creatif — Info', description: 'Carte + infos brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-full', label: 'E-commerce — Pleine', description: 'Carte pleine largeur verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-info', label: 'E-commerce — Info', description: 'Carte + infos verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-full', label: 'Glass — Pleine', description: 'Carte glass dark', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-info', label: 'Glass — Info', description: 'Carte + infos glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  search: [
    { id: 'startup', label: 'Startup', description: 'Recherche indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate', label: 'Corporate', description: 'Recherche navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe', label: 'Luxe', description: 'Recherche dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative', label: 'Creatif', description: 'Recherche brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce', label: 'E-commerce', description: 'Recherche verte', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass', label: 'Glass', description: 'Recherche glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  'comparison-table': [
    { id: 'startup-table', label: 'Startup — Tableau', description: 'Tableau comparatif indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-cards', label: 'Startup — Cards', description: 'Cards par colonne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-table', label: 'Corporate — Tableau', description: 'Navy, tableau pro', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-cards', label: 'Corporate — Cards', description: 'Navy, cards comparaison', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-table', label: 'Luxe — Tableau', description: 'Doré, tableau élégant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-cards', label: 'Luxe — Cards', description: 'Doré, cards raffinées', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-table', label: 'Créatif — Tableau', description: 'Brutaliste, tableau bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-cards', label: 'Créatif — Cards', description: 'Néobrutalist, cards offset', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-table', label: 'E-commerce — Tableau', description: 'Vert, tableau confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-cards', label: 'E-commerce — Cards', description: 'Vert, cards vérifiées', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-table', label: 'Glass — Tableau', description: 'Dark, tableau glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-cards', label: 'Glass — Cards', description: 'Glass, cards glow', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  form: [
    { id: 'startup-default', label: 'Startup — Defaut', description: 'Formulaire empile indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-split', label: 'Startup — Split', description: 'Infos + formulaire indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-default', label: 'Corporate — Defaut', description: 'Formulaire empile navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'corporate-split', label: 'Corporate — Split', description: 'Infos + formulaire navy', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'luxe-default', label: 'Luxe — Defaut', description: 'Formulaire dore elegant', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-split', label: 'Luxe — Split', description: 'Infos + formulaire dore', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-default', label: 'Creatif — Defaut', description: 'Formulaire brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-split', label: 'Creatif — Split', description: 'Infos + formulaire brutaliste', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-default', label: 'E-commerce — Defaut', description: 'Formulaire vert confiance', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-split', label: 'E-commerce — Split', description: 'Infos + formulaire vert', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-default', label: 'Glass — Defaut', description: 'Formulaire glass glow', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-split', label: 'Glass — Split', description: 'Infos + formulaire glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  'collection-list': [
    { id: 'startup-grid', label: 'Startup — Grille', description: 'Grille CMS indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-list', label: 'Startup — Liste', description: 'Liste CMS indigo', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-grid', label: 'Corporate — Grille', description: 'Grille CMS navy', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-list', label: 'Corporate — Liste', description: 'Liste CMS navy', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-grid', label: 'Luxe — Grille', description: 'Grille CMS doree', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'luxe-list', label: 'Luxe — Liste', description: 'Liste CMS doree', previewStyle: { background: 'dark', paddingY: 'lg' } },
  ],

  // ─── E-commerce ───

  'product-detail': [
    { id: 'startup-split', label: 'Startup — Split', description: 'Fiche produit split, moderne', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-gallery', label: 'Startup — Galerie', description: 'Fiche produit galerie', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-split', label: 'Corporate — Split', description: 'Fiche produit split, pro', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-gallery', label: 'Corporate — Galerie', description: 'Fiche produit galerie pro', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-split', label: 'Luxe — Split', description: 'Fiche produit split, luxe', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'luxe-gallery', label: 'Luxe — Galerie', description: 'Fiche produit galerie luxe', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'creative-split', label: 'Creatif — Split', description: 'Fiche produit split, bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-gallery', label: 'Creatif — Galerie', description: 'Fiche produit galerie bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-split', label: 'E-commerce — Split', description: 'Fiche produit split, standard', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-gallery', label: 'E-commerce — Galerie', description: 'Fiche produit galerie', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-split', label: 'Glass — Split', description: 'Fiche produit split, glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-gallery', label: 'Glass — Galerie', description: 'Fiche produit galerie glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  cart: [
    { id: 'startup-slide', label: 'Startup — Slide', description: 'Panier panneau lateral', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-page', label: 'Startup — Page', description: 'Panier page entiere', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-slide', label: 'Corporate — Slide', description: 'Panier slide pro', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-page', label: 'Corporate — Page', description: 'Panier page pro', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-slide', label: 'Luxe — Slide', description: 'Panier slide luxe', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'luxe-page', label: 'Luxe — Page', description: 'Panier page luxe', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'creative-slide', label: 'Creatif — Slide', description: 'Panier slide bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-page', label: 'Creatif — Page', description: 'Panier page bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-slide', label: 'E-commerce — Slide', description: 'Panier slide standard', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-page', label: 'E-commerce — Page', description: 'Panier page standard', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-slide', label: 'Glass — Slide', description: 'Panier slide glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-page', label: 'Glass — Page', description: 'Panier page glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
  checkout: [
    { id: 'startup-steps', label: 'Startup — Multi-etapes', description: 'Checkout 3 etapes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'startup-single', label: 'Startup — Page unique', description: 'Checkout une page', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-steps', label: 'Corporate — Multi-etapes', description: 'Checkout 3 etapes pro', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'corporate-single', label: 'Corporate — Page unique', description: 'Checkout une page pro', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'luxe-steps', label: 'Luxe — Multi-etapes', description: 'Checkout 3 etapes luxe', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'luxe-single', label: 'Luxe — Page unique', description: 'Checkout une page luxe', previewStyle: { background: 'dark', paddingY: 'lg' } },
    { id: 'creative-steps', label: 'Creatif — Multi-etapes', description: 'Checkout 3 etapes bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'creative-single', label: 'Creatif — Page unique', description: 'Checkout une page bold', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-steps', label: 'E-commerce — Multi-etapes', description: 'Checkout 3 etapes', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'ecommerce-single', label: 'E-commerce — Page unique', description: 'Checkout une page', previewStyle: { background: 'white', paddingY: 'md' } },
    { id: 'glass-steps', label: 'Glass — Multi-etapes', description: 'Checkout 3 etapes glass', previewStyle: { background: 'dark', paddingY: 'md' } },
    { id: 'glass-single', label: 'Glass — Page unique', description: 'Checkout une page glass', previewStyle: { background: 'dark', paddingY: 'md' } },
  ],
}
